title: "YSAS4331 Site"
author: "YSAS4331"

plugins:
  - jekyll-polyglot

languages:
  - en
  - ja
default_lang: "en"
exclude_from_localization:
  - assets
  - images

url: "https://ysas4331.github.io"
baseurl: ""

markdown: kramdown

# ここから追加
# 記事のパーマリンクを言語ごとに /en/スラッグ/ 形式にする
collections:
  posts:
    output: true
    permalink: /:lang/:slug/
